// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaPf3kP8VPma15-_wV4ZBvnfosKCra24A',
    appId: '1:828459923042:web:5c78289d93ebf97df0033b',
    messagingSenderId: '828459923042',
    projectId: 'nasr-isp',
    authDomain: 'nasr-isp.firebaseapp.com',
    storageBucket: 'nasr-isp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8_pRYoQacxj1dh61aSd9-gnjh9has7Eg',
    appId: '1:828459923042:android:0c92bdda612d008cf0033b',
    messagingSenderId: '828459923042',
    projectId: 'nasr-isp',
    storageBucket: 'nasr-isp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBREVhCxOMfKR8F_VQBSI3Fp-AQby2cCvs',
    appId: '1:828459923042:ios:cccd4439c7c8c759f0033b',
    messagingSenderId: '828459923042',
    projectId: 'nasr-isp',
    storageBucket: 'nasr-isp.firebasestorage.app',
    iosBundleId: 'com.example.nasrIsp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaPf3kP8VPma15-_wV4ZBvnfosKCra24A',
    appId: '1:828459923042:web:8d896d8eedc51351f0033b',
    messagingSenderId: '828459923042',
    projectId: 'nasr-isp',
    authDomain: 'nasr-isp.firebaseapp.com',
    storageBucket: 'nasr-isp.firebasestorage.app',
  );
}
